name: Deploy Azure Function App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # No instalamos npm aquÃ­ para no inflar el ZIP

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Set up Node.js version'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: 'npm install and build'
      run: |
        pushd ./hb-catalog-api
        npm install --production
        popd
    
    - name: ðŸš€ Deploy Azure Function App
      uses: azure/functions-action@v1
      with:
       app-name: hb-catalog-api-7856
       package: ./hb-catalog-api
